### ISSUE TITLE
Was IE8 support abandoned?

### ISSUE THREAD

**Issue by vsalbuq** [BankFacil/vanilla-masker#22]
I've tested build and lib files. None of them worked. The error message is:

> 'target' is null or not an object.

It happens when it gets to the last line of this part:

```javascript
VanillaMasker.prototype.bindElementToMask = function(maskFunction) {
    var that = this,
        onType = function(e) {
            var source = e.target || e.srcElement;
```
Error line: **55**.

I've tried to figure it out by myself, but I couldn't.

**Comment by leandroadacosta** [comment]
Can I close it issue?

**Comment by vsalbuq** [comment]
Closed!

**Comment by leandroadacosta** [comment]
\o/!
