### ISSUE TITLE
Bower installation issue

### ISSUE THREAD

**Issue by ImBobby** [BankFacil/vanilla-masker#28]
Tried to install vanilla-masker via bower and I get this
```
bower EMALFORMED    Failed to read /var/folders/1y/4n2m7zk15fd_jkg3fc7pdprh0000gn/T/bobby/bower/vanilla-masker-2639-PfxX5g/bower.json
```

I ran [jsonlint](http://jsonlint.com/) to the bower.json and you [have extra comma in line 15](https://github.com/BankFacil/vanilla-masker/blob/master/bower.json#L15).

**Comment by caio-ribeiro-pereira** [comment]
I fix this extra comma issue, could you check it again?

**Comment by ImBobby** [comment]
Still having the issue even after cleaning bower cache. Also I did try searching this package through [the bower registry](http://bower.io/search/?q=masker) and the last update is 4 weeks ago. I think you should push a new tag `1.6.1` to fix this issue.

**Comment by caio-ribeiro-pereira** [comment]
@leandroadacosta could you do this, please?

**Comment by leandroadacosta** [comment]
@caio-ribeiro-pereira "xahcomigo" :)

**Comment by leandroadacosta** [comment]
Solved. https://github.com/BankFacil/vanilla-masker/commit/c16bbdb9695aa0acf85c2fff200a3bf12fa54036
