### ISSUE TITLE
Opera Mini Test

### ISSUE THREAD

**Issue by ImBobby** [BankFacil/vanilla-masker#30]
I notice test Opera mini is in the todo so, I ran a test using Opera Mini on Android 4.1.2 and also on [opera mini simulator](https://dev.opera.com/articles/installing-opera-mini-on-your-computer/). The test case was
```Javascript
VMasker(elem).maskPattern('999-SSS');
```
both Opera Minis fail to mask the input and from the blog it appears that Opera Mini [doesn't support keyup event](https://dev.opera.com/articles/opera-mini-and-javascript/#unsupporteddom).

**Comment by leandroadacosta** [comment]
For now, we won't support it. Sorry :disappointed:
