### ISSUE TITLE
Suport for NPM

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [BankFacil/vanilla-masker#32]
Now libs like browserify and webpack enable load node scripts as js client-side libs, so it'll be good publish this lib into npmjs.org too

**Comment by caio-ribeiro-pereira** [comment]
To do this, you just need to create a npm account, because the vanilla-masker code runs into node environment because of UMD code

**Comment by caio-ribeiro-pereira** [comment]
@leandroadacosta I added CommomJS support (https://github.com/BankFacil/vanilla-masker/commit/5749892063d3f7f9f3c93dd1207ee7ae9470d112), but to finish this mission, you need to publish this module into npmjs.org using a BankFacil accounts, could you do that? And when you finish please update the build, version and readme because I can't do this now, I'm not using my notebook. Thanks!

**Comment by caio-ribeiro-pereira** [comment]
This gist will help you to publish a node module.
https://gist.github.com/coolaj86/1318304

**Comment by leandroadacosta** [comment]
It is here my friend :) https://www.npmjs.com/package/vanilla-masker \o

**Comment by caio-ribeiro-pereira** [comment]
Very nice my brother!
