### ISSUE TITLE
question: why can't I mask not-input elements?

### ISSUE THREAD

**Issue by felipebernardes** [BankFacil/vanilla-masker#50]
Hello folks,

I'm trying to use maskMoney in a paragraph element (because I don't want the user to be able to edit it's content) but it does results in the following error:

Uncaught TypeError: Cannot read property 'length' of undefined at g.bindElementToMask

Could you please explain me why this is happening?

**Comment by matheusca** [comment]
Let me understand.

Will you try use `maskMoney` in a tag `<p>`?

**Comment by felipebernardes** [comment]
@matheusca , I want to mask a non-input element's content because I want to show a not-masked stored data.

**Comment by matheusca** [comment]
@felipebernardes You can't use `maskMoney` to do what you want in a paragraph, but I'll explain how you can do it.

You might use `toMoney` method getting the paragraph text with `innerText`.

For instance:

```js
text_from_id = document.getElementById('test').innerText; 

console.log(VMasker.toMoney(text_from_id));
```

You could see more about here: https://github.com/BankFacil/vanilla-masker#money-format

After you transform your text in a "money format" you could put in a variable and change your text from the new.

Here the code that you check it out: https://github.com/BankFacil/vanilla-masker/blob/master/lib/vanilla-masker.js#L122

Did it solve your problem?

**Comment by felipebernardes** [comment]
Hey @matheusca, it worked!

Thank you very much for helping me out solving this. VanillaMasker rocks!

**Comment by leandroadacosta** [comment]
@matheusca be careful about the sintax :) `text_from_id` is wrong in JS, the right way is `textFromId`. You are coding in Ruby all day, gzuz.... hehe

**Comment by regishideki** [comment]
It is not about syntax, it is about naming convention. The syntax is right =)
