### ISSUE TITLE
Update Meteor package

### ISSUE THREAD

**Issue by frabrunelle** [BankFacil/vanilla-masker#54]
Could you please update the `bankfacil:vanilla-masker` package on [Atmosphere](https://atmospherejs.com/bankfacil/vanilla-masker)?

It's currently at version 1.0.2 instead of 1.1.0.

Thank you :smile: 

Also, this is unrelated but I would just like to mention that there is one minor bug that I am experiencing: I am not able to do a copy paste using keyboard shortcuts. For example, I am not able to select the text in the input field by doing <kbd>⌘</kbd> + <kbd>a</kbd>. And when I select the text with my cursor, it doesn't work when I try to copy it to my clipboard by doing <kbd>⌘</kbd> + <kbd>c</kbd>. Overall I still prefer this package compared to the other I tried, but it would be nice to fix this issue :smiley:

**Comment by grsabreu** [comment]
+1 
Yeah, guys, do this.
