### ISSUE TITLE
Placeholder option for toPattern doesn't seem to be working

### ISSUE THREAD

**Issue by rgriffith** [BankFacil/vanilla-masker#55]
Using v1.1.0, the example `toPattern` with placeholder code:

```
VMasker.toPattern('4', {pattern: "(999) 999-9999", placeholder: "x"})
```

produces the following output 

```
(4
```

Additionally, it would be nice if one could provide a placeholder option to the custom `maskPattern` method.

**Comment by leandroadacosta** [comment]
@rgriffith this behavior is right :)
