### ISSUE TITLE
Min an max value in pattern

### ISSUE THREAD

**Issue by maraism** [BankFacil/vanilla-masker#61]
Hi,

Is it possible to have min and max values for pattern ?
For example in input[text] with time 99:99 
First part of pattern : min 00 max 23
Last part of pattern : min 00 max 59 
15:50 => OK
00:01 => OK
40:20 => NOK
23:60 => NOK

Thanks
Maxime

**Comment by leandroadacosta** [comment]
@maraism it isn't the concern of VM, you can do it coding other JS with this responsibility.

**Comment by leandroadacosta** [comment]
@maraism see this issue #64
