### ISSUE TITLE
Mask H:i:s

### ISSUE THREAD

**Issue by des1roer** [BankFacil/vanilla-masker#64]
How i can use time mask?

**Comment by caio-ribeiro-pereira** [comment]
@des1roer you can use: `VMasker.toPattern(112233, "99:99:99");`, if you want to parse date and time, I recommend you to use moment.js lib (http://momentjs.com)

**Comment by des1roer** [comment]
if i write 99:99 user can write 41:89. i wona user can write 23:59 max

**Comment by caio-ribeiro-pereira** [comment]
this kind of mask we don't have yet, but feel free to make a PR improving this mask :)

**Comment by willycamargo** [comment]
You can validate these data on element blur

eg:
```
var element = document.querySelector("input")

VMasker(element).maskPattern("99:99")
element.addEventListener('blur', function() {
    var self = this
	var full = self.value
    var splited = full.split(':')

    if (splited[0] > 23 || !splited[1] || splited[1] > 59) {
        self.value = ''
	}
})
```
https://jsfiddle.net/jsove2mr/

**Comment by caio-ribeiro-pereira** [comment]
Just improving the @willycamargo code:
```
var element = document.querySelector("input");
VMasker(element).maskPattern("99:99:99");
element.addEventListener('blur', function(e) {
   var time = this.value.split(":");
   if (time[0] > 23 || time[1] > 59 || time[2] > 59) {
        this.value = "";
   }
};
```

**Comment by willycamargo** [comment]
Great @caio-ribeiro-pereira !

I got this code in the system that I am working and I just copied and pasted here. I forgot to refactor the code. :sweat_smile:

**Comment by leandroadacosta** [comment]
Great guys.
