### ISSUE TITLE
How can I know that the masker stripped a value?

### ISSUE THREAD

**Issue by gabrielpugliese-luizalabs** [BankFacil/vanilla-masker#66]
For eg, I have the mask:
```
(99) 9999-9999
````
If I input:
```
(11) 1234-56789
```
The 9 will be stripped. But I the event when that happens. How can I do that easily?

**Comment by leandroadacosta** [comment]
Fixed by #57

**Comment by gabrielpugliese-luizalabs** [comment]
Thanks! :clap: :clap: :clap: :clap:
