### ISSUE TITLE
money with delimiter

### ISSUE THREAD

**Issue by keown** [BankFacil/vanilla-masker#88]
i need to mask a money field but i don't need any delimiter. i've tried with

```js
VMasker.toMoney(e.target.value, {
          precision: 2,
          separator: '.',
          delimiter: ''
        });
```

and

```js
VMasker.toMoney(e.target.value, {
          precision: 2,
          separator: '.',
          delimiter: null
        });
```

but they both don't work. any tips?

**Comment by regishideki** [comment]
I think it happens because there is a default value in this line:
https://github.com/BankFacil/vanilla-masker/blob/master/lib/vanilla-masker.js#L27

**Comment by scudelletti** [comment]
You can try something like [Carriage Return](http://www.fileformat.info/info/unicode/char/000d/index.htm) unicode like `\u000D`.

```javascript
VMasker.toMoney(1234567890, {
  precision: 2,
  separator: '.',
  delimiter: '\u000D'
});
```

PS: This is a ugly an horrible hack.

**Comment by keown** [comment]
thanks @scudelletti !
both `\u000D` and `\u200B` works 👍
